### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by nakigoe** [Bassonrichard/SocialMediaSharingBlazor#1]
A button appears, but nothing happens on pressing.
Empty project?

**Comment by Bassonrichard** [comment]
What browser are you using and on what device, not all browsers and devices are supported as support is linked to the Navigator Share browser API? 

You can find more details on that here:
https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share#browser_compatibility

You can also have a look at the example project if you are having trouble implementing the share button
https://github.com/Bassonrichard/SocialMediaSharingBlazor/tree/main/examples/BlazorWebAssembly

**Comment by nakigoe** [comment]
Hi Richard, thank you for the reply!
I am on Chrome, Windows 7
the screen was empty at first, and when I set the button dimensions to
400x200px it was one empty button on the screen.

**Comment by Bassonrichard** [comment]
Hi , 
This library isn't meant to be a UI component. 

This library just gives functionality to the butter you choose to implement so you will have to provide a button that calls the function this library provides. 

You can have a look at the example again to see how you can makes calls to the library here:
[Example](https://github.com/Bassonrichard/SocialMediaSharingBlazor/blob/main/examples/BlazorWebAssembly/Pages/Index.razor)

I also hosted an example on netlify for you to try out.
https://socialmediasharingblazor.netlify.app/
