### ISSUE TITLE
FaceBook Text Not Pulling Through

### ISSUE THREAD

**Issue by kenneymyers** [Bassonrichard/SocialMediaSharingBlazor#2]
This works exceptionally well for Twitter, Email, and many apps. However, the text does not pull through in FaceBook only the url does. Is there something special that needs to be done to make that work properly? I'll keep researching but as far as I can tell that is the only issue.

**Comment by Bassonrichard** [comment]
Hi, unfortunately it looks like Facebook does not allow the pre-populating of text. They want users to manually enter the text they want to share. 

https://developers.facebook.com/docs/apps/review/prefill

I don't know if this suffices your use case but maybe using something like og tags in the URL you are sharing ?
